# Site settings
title: QMLab
email: qmlab.contact@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  QMLab: Global Collaboration on Quamtum Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qmlab.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: QuantumMLLab

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Global Collaboration on Quamtum Machine Learning"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""